type Bid {
    robot: Int  
    distance: Int
    request: Request
}

type Request {
    robot: Int
    timestamp: String!
    source: String!
    destination: String!
    sender: String!
    recipient: String!
    state: String!
    age: String
    bidExpiry: String
    priority: Int
    bids: [Bid]
}

type User {
    username: String! @id
    email: String!
}

type Robot {
    location: String
    status: String
}

type Path {
    beacon: Beacon
    destBeacon: Int
    distance: Int
}

type Junction {
    beacons: [Int]
}

type Beacon {
    junction: Int
    status: String
    paths: [Path] @relation
}

type Query {
    allRequests: [Request!]
    allUsers: [User!]
    allRobots: [Robot!]
    allJunctions: [Junction!]
    allBeacons: [Beacon!]
    requestsByState(state: String!): [Request!]
}

